import { setLocale } from "@/paraglide/runtime";
import { RestApiProvider } from "@/pkg/library/rest-api";
import { UiProvider } from "@/pkg/library/ui";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// interface
interface IProps {
  children: React.ReactNode;
  params: Promise<{ locale: "en" | "de" }>;
}

export default async function RootLayout(props: Readonly<IProps>) {
  const { children, params } = props;
  const { locale } = await params;

  setLocale(locale);

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UiProvider>
          <RestApiProvider>{children}</RestApiProvider>
        </UiProvider>
      </body>
    </html>
  );
}
